### ISSUE TITLE
License for version 0.9.0 and lower

### ISSUE THREAD

**Issue by pinty** [request/caseless#28]
Hello @mikeal 

Currently I'm using this component under version 0.9.0 and 0.6.0 which seems not to be present on your repository. The only information regarding the license for the version 0.9.0 and lower ones is the statement present inside the package.json file, which is "BSD".
Would you please be more specific regarding the license for the version 0.9.0 and older ones? What license will apply for those versions, Apache 2.0 (as I can see is the master license) or the BSD one? And in case of BSD which version?

Thank you!

**Comment by mikeal** [comment]
Honestly, we had intended to always license Apache-2 but for some reason had the wrong thing early on.

You'd want to consult a legal expert to determine what the actual license should be considered give that the only notice was for a non-SPDX license ref :(

If you're worried about licensing I would take 0.10.x or higher since it is very clearly Apache-2 licensed.
